/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeService */

#ifndef _Included_NativeService
#define _Included_NativeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeService
 * Method:    insert
 * Signature: (LUser;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeService_insert
  (JNIEnv *, jobject, jobject);

/*
 * Class:     NativeService
 * Method:    view
 * Signature: (LUser;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_NativeService_view
  (JNIEnv *, jobject, jobject);

/*
 * Class:     NativeService
 * Method:    insertList
 * Signature: (Ljava/util/ArrayList;LUser;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeService_insertList
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
